#Drone CI
kind: pipeline
type: docker
name: blog.magnatox.com

steps:
  - name: submodules
    image: alpine/git:latest
    commands:
      - git submodule update --init --recursive --remote
  - name: build-drafts
    image: plugins/hugo
    settings:
      hugo_version: 0.100.1
      extended: true
      pull: always
      url: https://blog.magnatox.com
      source: blog/
      buildDrafts: true
    when:
      branch:
        exclude:
          - master
  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.100.1
      extended: true
      pull: always
      url: https://blog.magnatox.com
      source: blog/
      buildDrafts: false
    when:
      branch:
        - master
      event:
        - push
        - rollback
        - tag
        - promote
  - name: deploy
    image: drillster/drone-rsync
    target:
    settings:
      hosts:
        from_secret: remote_hosts
      source: blog/public/*
      recursive: true
      user:
        from_secret: remote_user
      key:
        from_secret: remote_key
      port:
        from_secret: remote_port
      target:
        from_secret: remote_target
      script:
        - cd /home/drone/docker/hugo/blog
        - docker compose down
        - docker compose pull
        - docker compose up -d
    when:
      branch:
        - master
      event:
        - push
        - rollback
        - tag
        - promote
