baseURL = "https://blog.magnatox.com"
languageCode = "en-us"
title = "Tony Martinez Blog"
autho = "Tony Martinez"
theme = "blackburn"
paginate = 10

[indexes]
tag = "tags"
topic = "topics"

[params]
dateFormat = "2006 Jan 02, 15:04"
readingTime = true
custom_css = ["style.css"]
[menu]
	[[menu.main]]
		name = "Home"
		identifier = "home"
		pre = "<i class='fa fa-home fa-fw'></i>"
		url = "/"
		weight = 1
	[[menu.main]]
		name = "About"
		identifier = "about"
		pre = "<i class='fa fa-user fa-fw'></i>"
		url = "/about/"
		weight = 2
	[[menu.main]]
		identifier = "post"
		name = "Posts"
		pre = "<i class='fa fa-list fa-fw'></i>"
		url = "/post/"
		weight = 3
	[[menu.main]]
		identifier = "tags"
		name = "Tags"
		url = "/tags/"
		weight = 4
	[[menu.main]]
		identifier = "links"
		name = "Links"
		url = "/links/"
		weight = 5

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
