baseURL: https://blog.magnatox.com
languageCode: en-us
defaultContentLanguage: en
title: Tony Martinez Blog
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:/filename/

imaging:
  quality: 99

params:
  dateFormat: 2006-01-02
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Posts
      url: /posts/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Links
      url: /links/
      weight: 5
    - name: RSS
      url: /index.xml
      weight: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
